package com.liguang.rcs.db.dao;

import com.liguang.rcs.db.domain.RcsPermission;
import com.liguang.rcs.db.domain.RcsPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RcsPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     */
    long countByExample(RcsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     */
    int deleteByExample(RcsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     */
    int insert(RcsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     */
    int insertSelective(RcsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsPermission selectOneByExample(RcsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsPermission selectOneByExampleSelective(@Param("example") RcsPermissionExample example, @Param("selective") RcsPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<RcsPermission> selectByExampleSelective(@Param("example") RcsPermissionExample example, @Param("selective") RcsPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     */
    List<RcsPermission> selectByExample(RcsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") RcsPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     */
    RcsPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RcsPermission record, @Param("example") RcsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RcsPermission record, @Param("example") RcsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RcsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RcsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") RcsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}