package com.liguang.rcs.db.dao;

import com.liguang.rcs.db.domain.RcsRole;
import com.liguang.rcs.db.domain.RcsRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RcsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     */
    long countByExample(RcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     */
    int deleteByExample(RcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     */
    int insert(RcsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     */
    int insertSelective(RcsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsRole selectOneByExample(RcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsRole selectOneByExampleSelective(@Param("example") RcsRoleExample example, @Param("selective") RcsRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<RcsRole> selectByExampleSelective(@Param("example") RcsRoleExample example, @Param("selective") RcsRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     */
    List<RcsRole> selectByExample(RcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") RcsRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     */
    RcsRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RcsRole record, @Param("example") RcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RcsRole record, @Param("example") RcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RcsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RcsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") RcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}