package com.liguang.rcs.db.dao;

import com.liguang.rcs.db.domain.RcsRegion;
import com.liguang.rcs.db.domain.RcsRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RcsRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     */
    long countByExample(RcsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     */
    int deleteByExample(RcsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     */
    int insert(RcsRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     */
    int insertSelective(RcsRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsRegion selectOneByExample(RcsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsRegion selectOneByExampleSelective(@Param("example") RcsRegionExample example, @Param("selective") RcsRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<RcsRegion> selectByExampleSelective(@Param("example") RcsRegionExample example, @Param("selective") RcsRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     */
    List<RcsRegion> selectByExample(RcsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") RcsRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     */
    RcsRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RcsRegion record, @Param("example") RcsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RcsRegion record, @Param("example") RcsRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RcsRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RcsRegion record);
}