package com.liguang.rcs.db.dao;

import com.liguang.rcs.db.domain.RcsUser;
import com.liguang.rcs.db.domain.RcsUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RcsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     */
    long countByExample(RcsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     */
    int deleteByExample(RcsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     */
    int insert(RcsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     */
    int insertSelective(RcsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsUser selectOneByExample(RcsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsUser selectOneByExampleSelective(@Param("example") RcsUserExample example, @Param("selective") RcsUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<RcsUser> selectByExampleSelective(@Param("example") RcsUserExample example, @Param("selective") RcsUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     */
    List<RcsUser> selectByExample(RcsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") RcsUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     */
    RcsUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RcsUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RcsUser record, @Param("example") RcsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RcsUser record, @Param("example") RcsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RcsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RcsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") RcsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcs_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}